sudo: required
services:
  - docker

env:
    global:
      - PRODUCT=tarantool-cbench
    matrix:
      - OS=el DIST=6 PACK=rpm
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=fedora DIST=24 PACK=rpm
#      - OS=fedora DIST=rawhide PACK=rpm
      - OS=ubuntu DIST=precise PACK=deb
      - OS=ubuntu DIST=trusty PACK=deb
      - OS=ubuntu DIST=wily PACK=deb
      - OS=ubuntu DIST=xenial PACK=deb
      - OS=debian DIST=wheezy PACK=deb
      - OS=debian DIST=jessie PACK=deb
      - OS=debian DIST=stretch PACK=deb
#      - OS=debian DIST=sid PACK=deb

script:
  - git clone https://github.com/tarantool/build.git
  - PACKAGECLOUD_REPO=tarantool/1_6 REPO_PREFIX=1.6 ./build/pack/travis.sh
  - PACKAGECLOUD_REPO=tarantool/1_7 REPO_PREFIX=1.7 ./build/pack/travis.sh

notifications:
  email: true
  irc: false
